title : Marwen FATNASSI
logo: /assets/img/CV_github.PNG
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal #https://pages.github.com/themes/

Principales compétences :

    AI & BI
    Data Mining & Data Analysis
    Big Data

Languages :

    Anglais (Full Professional)
    Français (Native or Bilingual)
    Arabe (Native or Bilingual)
    Allemand (Elementary)

